"use client";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, ChevronDown, Circle, Clock3, Command, Copy, Filter, Inbox, LayoutList, MoreHorizontal, Plus, Search, Settings2, Sparkles, Tag, Trash2, X, Zap } from "lucide-react";
import { useTaskStore } from "@/lib/store";
import type { Priority, Task, TaskStatus, View } from "@/lib/types";

const priorityMeta:Record<Priority,{label:string;mark:string}>={none:{label:"No priority",mark:""},low:{label:"Low",mark:"↓"},medium:{label:"Medium",mark:"→"},high:{label:"High",mark:"↑"},urgent:{label:"Urgent",mark:"!!"}};
const views:{id:View;label:string;icon:typeof Inbox}[]=[{id:"inbox",label:"Inbox",icon:Inbox},{id:"today",label:"Today",icon:CalendarDays},{id:"upcoming",label:"Upcoming",icon:Clock3},{id:"completed",label:"Completed",icon:Check}];

function dateLabel(date:string|null){if(!date)return "No date"; const d=new Date(`${date}T12:00:00`); const t=new Date(); const td=t.toISOString().slice(0,10); const tm=new Date(t.getTime()+86400000).toISOString().slice(0,10); if(date===td)return "Today"; if(date===tm)return "Tomorrow"; return d.toLocaleDateString(undefined,{month:"short",day:"numeric"});}
function matches(task:Task,view:View,filter:any){const q=filter.query.toLowerCase(); if(q&&!`${task.title} ${task.notes} ${task.project} ${task.tags.join(" ")}`.toLowerCase().includes(q))return false; if(filter.priority!=="all"&&task.priority!==filter.priority)return false;if(filter.status!=="all"&&task.status!==filter.status)return false;if(filter.project!=="all"&&task.project!==filter.project)return false;if(filter.tag!=="all"&&!task.tags.includes(filter.tag))return false; const now=new Date().toISOString().slice(0,10); if(view==="today"&&task.dueDate!==now)return false;if(view==="upcoming"&&(!task.dueDate||task.dueDate<=now))return false;if(view==="completed"&&task.status!=="done")return false;return view!=="completed"||task.status==="done";}

export default function Home(){
 const {tasks,view,setView,filter,setFilter,selectedId,select,add,toggle,remove,duplicate,clearCompleted,update}=useTaskStore();
 const [quick,setQuick]=useState(""); const [showFilters,setShowFilters]=useState(false); const [mobileDetail,setMobileDetail]=useState(false);
 useEffect(()=>{useTaskStore.getState().setHydrated(true); const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.getElementById("global-search")?.focus()} if(e.key==="n"&&!e.metaKey&&!e.ctrlKey&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();document.getElementById("quick-add")?.focus()}}; window.addEventListener("keydown",key); return()=>window.removeEventListener("keydown",key)},[]);
 const visible=useMemo(()=>tasks.filter(t=>matches(t,view,filter)),[tasks,view,filter]); const selected=tasks.find(t=>t.id===selectedId)||null;
 const projects=[...new Set(tasks.map(t=>t.project))]; const tags=[...new Set(tasks.flatMap(t=>t.tags))]; const open=tasks.filter(t=>t.status!=="done").length; const done=tasks.filter(t=>t.status==="done").length;
 const create=()=>{if(!quick.trim())return;add({title:quick.trim()});setQuick("");};
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><div className="brandmark"><Zap size={17}/></div><span>Taskflow</span></div><button className="new-task" onClick={()=>document.getElementById("quick-add")?.focus()}><Plus size={17}/> New task <kbd>N</kbd></button>
   <nav className="nav">{views.map(v=>{const Icon=v.icon; const count=v.id==="completed"?done:v.id==="inbox"?open:undefined; return <button key={v.id} className={view===v.id?"nav-item active":"nav-item"} onClick={()=>setView(v.id)}><Icon size={17}/>{v.label}{count!==undefined&&<span className="count">{count}</span>}</button>})}</nav>
   <div className="side-section"><div className="side-title">Projects</div>{projects.map(p=><button className="project" key={p} onClick={()=>{setFilter({project:p});setView("inbox")}}><span className="dot"/>{p}</button>)}</div>
   <div className="side-bottom"><button className="nav-item"><Settings2 size={17}/> Settings</button><div className="profile"><div className="avatar">UR</div><div><b>Ukanna</b><span>Personal workspace</span></div><MoreHorizontal size={16}/></div></div>
  </aside>
  <section className="workspace"><header className="topbar"><div className="mobile-brand"><div className="brandmark"><Zap size={16}/></div>Taskflow</div><div className="search"><Search size={17}/><input id="global-search" value={filter.query} onChange={e=>setFilter({query:e.target.value})} placeholder="Search tasks, projects, tags..."/><kbd>⌘ K</kbd></div><button className="icon-btn"><Command size={18}/></button></header>
   <div className="content"><div className="list-pane"><div className="page-head"><div><p className="eyebrow">WORKSPACE</p><h1>{views.find(v=>v.id===view)?.label}</h1><p className="muted">{view==="today"?"Everything that needs attention today.":view==="upcoming"?"Tasks scheduled beyond today.":view==="completed"?"Your completed work.":"Your active task queue."}</p></div><div className="head-actions"><button className={showFilters?"small-btn active":"small-btn"} onClick={()=>setShowFilters(!showFilters)}><Filter size={15}/> Filter</button><button className="small-btn"><LayoutList size={15}/></button></div></div>
    {showFilters&&<div className="filters"><select value={filter.status} onChange={e=>setFilter({status:e.target.value as TaskStatus|"all"})}><option value="all">Any status</option><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option></select><select value={filter.priority} onChange={e=>setFilter({priority:e.target.value as Priority|"all"})}><option value="all">Any priority</option>{Object.entries(priorityMeta).filter(([x])=>x!=="none").map(([v,m])=><option key={v} value={v}>{m.label}</option>)}</select><select value={filter.project} onChange={e=>setFilter({project:e.target.value})}><option value="all">Any project</option>{projects.map(p=><option key={p}>{p}</option>)}</select>{filter.project!=="all"&&<button onClick={()=>setFilter({project:"all"})}><X size={14}/></button>}</div>}
    <div className="quick-add"><Plus size={18}/><input id="quick-add" value={quick} onChange={e=>setQuick(e.target.value)} onKeyDown={e=>e.key==="Enter"&&create()} placeholder="Add a task..."/><span>Press Enter</span></div>
    <div className="task-list">{visible.length===0?<div className="empty"><Sparkles size={22}/><b>No tasks found</b><span>Try another filter or create a new task.</span></div>:visible.map(t=><TaskRow key={t.id} task={t} selected={t.id===selectedId} onSelect={()=>{select(t.id);setMobileDetail(true)}} onToggle={()=>toggle(t.id)}/>)}</div>
    {view==="completed"&&done>0&&<button className="clear-completed" onClick={clearCompleted}><Trash2 size={14}/> Clear completed tasks</button>}
   </div><TaskDetail task={selected} update={update} remove={remove} duplicate={duplicate} toggle={toggle} mobile={mobileDetail} close={()=>setMobileDetail(false)}/></div>
  </section>
 </main>
}

function TaskRow({task,selected,onSelect,onToggle}:{task:Task;selected:boolean;onSelect:()=>void;onToggle:()=>void}){const p=priorityMeta[task.priority]; const sub=task.subtasks.length?`${task.subtasks.filter(s=>s.done).length}/${task.subtasks.length}`:null;return <button className={selected?"task-row selected":"task-row"} onClick={onSelect}><span className={`check ${task.status}`} onClick={e=>{e.stopPropagation();onToggle()}}>{task.status==="done"&&<Check size={12}/>}</span><span className="task-main"><span className={task.status==="done"?"task-title done":"task-title"}>{task.title}</span><span className="task-meta">{task.project} {task.tags.slice(0,2).map(x=><span className="tag" key={x}>#{x}</span>)}{sub&&<span> · {sub}</span>}</span></span><span className={`priority ${task.priority}`}>{p.mark}</span><span className="due">{dateLabel(task.dueDate)}{task.dueTime&&` · ${task.dueTime}`}</span></button>}

function TaskDetail({task,update,remove,duplicate,toggle,mobile,close}:{task:Task|null;update:(id:string,input:Partial<Task>)=>void;remove:(id:string)=>void;duplicate:(id:string)=>void;toggle:(id:string)=>void;mobile:boolean;close:()=>void}){if(!task)return <aside className="detail empty-detail"><Sparkles size={24}/><b>Select a task</b><span>Choose a task to inspect and edit its details.</span></aside>; const done=task.subtasks.filter(s=>s.done).length; const set=(input:Partial<Task>)=>update(task.id,input); return <aside className={mobile?"detail mobile-open":"detail"}><div className="detail-head"><span className="eyebrow">TASK DETAILS</span><div><button className="icon-btn" onClick={()=>duplicate(task.id)} title="Duplicate"><Copy size={16}/></button><button className="icon-btn" onClick={close}><X size={17}/></button></div></div><input className="detail-title" value={task.title} onChange={e=>set({title:e.target.value})}/><textarea className="notes" value={task.notes} onChange={e=>set({notes:e.target.value})} placeholder="Add notes..."/>
 <div className="detail-grid"><label>Status<select value={task.status} onChange={e=>set({status:e.target.value as TaskStatus})}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option></select></label><label>Priority<select value={task.priority} onChange={e=>set({priority:e.target.value as Priority})}>{Object.entries(priorityMeta).map(([v,m])=><option key={v} value={v}>{m.label}</option>)}</select></label><label>Due date<input type="date" value={task.dueDate??""} onChange={e=>set({dueDate:e.target.value||null})}/></label><label>Time<input type="time" value={task.dueTime??""} onChange={e=>set({dueTime:e.target.value||null})}/></label><label>Project<input value={task.project} onChange={e=>set({project:e.target.value})}/></label><label>Repeat<select value={task.recurring} onChange={e=>set({recurring:e.target.value as Task["recurring"]})}><option value="none">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label></div>
 <div className="detail-section"><div className="section-head"><b>Subtasks</b><span>{done}/{task.subtasks.length}</span></div>{task.subtasks.map(s=><label className="subtask" key={s.id}><input type="checkbox" checked={s.done} onChange={()=>set({subtasks:task.subtasks.map(x=>x.id===s.id?{...x,done:!x.done}:x)})}/><span>{s.title}</span></label>)}<button className="add-sub" onClick={()=>set({subtasks:[...task.subtasks,{id:crypto.randomUUID(),title:"New subtask",done:false}]})}><Plus size={14}/> Add subtask</button></div>
 <div className="detail-section"><div className="section-head"><b>Tags</b><Tag size={15}/></div><div className="tag-list">{task.tags.map(t=><span className="tag-chip" key={t}>#{t}</span>)}<button className="tag-chip add" onClick={()=>set({tags:[...task.tags,"new-tag"]})}>+ tag</button></div></div>
 <div className="detail-footer"><button className="delete-btn" onClick={()=>remove(task.id)}><Trash2 size={14}/> Delete</button><button className="complete-btn" onClick={()=>toggle(task.id)}>{task.status==="done"?<><Circle size={14}/> Reopen</>:<><Check size={14}/> Complete</>}</button></div></aside>}
